<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Cleaning</a></span><ul class="toc-item"><li><span><a href="#RawData-Info" data-toc-modified-id="RawData-Info-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>RawData Info</a></span></li></ul></li></ul></div>

**Import Libraries**

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt

import os
import numpy as np
import pandas as pd
from datetime import datetime
import time

import warnings
warnings.filterwarnings('ignore')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

---

**File Tree**

In [16]:
!tree

.
├── Python_Script.ipynb
├── files
│   ├── Draft\ 3---GDP.docx
│   └── GDP_Raw.csv
└── ~$aft\ 3---GDP.docx

1 directory, 4 files

## Data Cleaning

### RawData Info

In [9]:
df = pd.read_csv('GDP_Raw.csv')

df.shape
df.head(3)
df.tail(3)

(638, 5)

,year,level_1,level_2,level_3,value
0,1961,GDP In Chained (2015) Dollars,Goods Producing Industries,Manufacturing,0.6
1,1961,GDP In Chained (2015) Dollars,Goods Producing Industries,Construction,1.2
2,1961,GDP In Chained (2015) Dollars,Goods Producing Industries,Utilities,0.1
3,1961,GDP In Chained (2015) Dollars,Goods Producing Industries,Other Goods Industries,0.1
4,1961,GDP In Chained (2015) Dollars,Services Producing Industries,Wholesale & Retail Trade,3.1
5,1961,GDP In Chained (2015) Dollars,Services Producing Industries,Transportation & Storage,0.7
6,1961,GDP In Chained (2015) Dollars,Services Producing Industries,Accommodation & Food Services,0.2
7,1961,GDP In Chained (2015) Dollars,Services Producing Industries,Information & Communications,0.0
8,1961,GDP In Chained (2015) Dollars,Services Producing Industries,Finance & Insurance,0.7
9,1961,GDP In Chained (2015) Dollars,Services Producing Industries,Business Services,0.6
10,1961,GDP In Chained (2015) Dollars,Services Producing Industries,Other Services Industries,0.7
11,1962,GDP In Chained (2015) Dollars,Goods Producing Industries,Manufacturing,0.9
12,1962,GDP In Chained (2015) Dollars,Goods Producing Industries,Construction,0.4
13,1962,GDP In Chained (2015) Dollars,Goods Producing Industries,Utilities,0.4
14,1962,GDP In Chained (2015) Dollars,Goods Producing Industries,Other Goods Industries,0.2

,year,level_1,level_2,level_3,value
627,2018,GDP In Chained (2015) Dollars,Goods Producing Industries,Manufacturing,1.3
628,2018,GDP In Chained (2015) Dollars,Goods Producing Industries,Construction,-0.1
629,2018,GDP In Chained (2015) Dollars,Goods Producing Industries,Utilities,0.0
630,2018,GDP In Chained (2015) Dollars,Goods Producing Industries,Other Goods Industries,0.0
631,2018,GDP In Chained (2015) Dollars,Services Producing Industries,Wholesale & Retail Trade,0.3
632,2018,GDP In Chained (2015) Dollars,Services Producing Industries,Transportation & Storage,0.1
633,2018,GDP In Chained (2015) Dollars,Services Producing Industries,Accommodation & Food Services,0.1
634,2018,GDP In Chained (2015) Dollars,Services Producing Industries,Information & Communications,0.2
635,2018,GDP In Chained (2015) Dollars,Services Producing Industries,Finance & Insurance,0.7
636,2018,GDP In Chained (2015) Dollars,Services Producing Industries,Business Services,0.4
637,2018,GDP In Chained (2015) Dollars,Services Producing Industries,Other Services Industries,0.2

In [10]:
df.drop(columns = 'level_1', inplace=True)

In [13]:
df.rename(columns={'year': 'Year', 'level_2': 'Level1', 'level_3': 'Level2', 'value': 'Value'}, inplace=True)

In [14]:
df

     Year                         Level1                         Level2  Value
0    1961     Goods Producing Industries                  Manufacturing    0.6
1    1961     Goods Producing Industries                   Construction    1.2
2    1961     Goods Producing Industries                      Utilities    0.1
3    1961     Goods Producing Industries         Other Goods Industries    0.1
4    1961  Services Producing Industries       Wholesale & Retail Trade    3.1
..    ...                            ...                            ...    ...
633  2018  Services Producing Industries  Accommodation & Food Services    0.1
634  2018  Services Producing Industries   Information & Communications    0.2
635  2018  Services Producing Industries            Finance & Insurance    0.7
636  2018  Services Producing Industries              Business Services    0.4
637  2018  Services Producing Industries      Other Services Industries    0.2

[638 rows x 4 columns]